### ISSUE TITLE
Demon ne démarre pas après mise à jour 1.2.1 et 1.2.2

### ISSUE THREAD

**Issue by Medou31** [Jeedom-Zigate/jeedom-plugin-zigate#132]
Bonjour,

Constatant une mise à jour jeedom et une mise à jour du plugin zigate, j'ai lancé les mises à jour mais après que celles-ci se soient faite, le plugin Zigate me remonte que le démon n'a pas pu être lancé. 
J'ai alors effectué un redémarrage avec les logs en mode debug mais je n'arrive pas à comprendre d'où vient le problème.
Pourriez-vous m'aider ? 

Voici les logs.
```
[2019-01-06 18:42:42][ERROR][zigate] : Command 0x0042 failed Failed (ZigBee event codes) 128 : b''
[2019-01-06 18:42:42][ERROR][zigate] : Command 0x0045 failed Failed (ZigBee event codes) 128 : b''
[2019-01-07 09:18:09][ERROR] : Veuillez vérifier la configuration
[2019-01-07 20:08:10][ERROR][zigate] : Command 0x0092 failed Failed (ZigBee event codes) 21 : b''
[2019-02-14 11:17:44][ERROR] : Veuillez vérifier la configuration
[2019-02-14 10:19:18][ERROR][zigate](MainThread) : Failed to get network state
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 354, in need_discovery
if device.need_discovery():
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2627, in need_discovery
self.load_template()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2684, in load_template
self._bind_report()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2122, in _bind_report
self._zigate.bind_addr(self.addr, endpoint_id, 0x0006)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 952, in bind_addr
return self.bind(ieee, endpoint, cluster, dst_addr, dst_endpoint)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 940, in bind
dst_addr, dst_endpoint)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 924, in _bind_unbind
dst_addr_mode = self._choose_addr_mode(dst_addr)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 904, in _choose_addr_mode
if len(addr_ieee) == 4:
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 330, in <module>
version = z.get_version_text()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 756, in get_version_text
v = self.get_version(refresh)['version']
TypeError: 'NoneType' object is not subscriptable
[2019-02-14 10:20:18][ERROR][zigate](MainThread) : Failed to get network state
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 354, in need_discovery
if device.need_discovery():
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2627, in need_discovery
self.load_template()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2684, in load_template
self._bind_report()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2122, in _bind_report
self._zigate.bind_addr(self.addr, endpoint_id, 0x0006)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 952, in bind_addr
return self.bind(ieee, endpoint, cluster, dst_addr, dst_endpoint)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 940, in bind
dst_addr, dst_endpoint)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 924, in _bind_unbind
dst_addr_mode = self._choose_addr_mode(dst_addr)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 904, in _choose_addr_mode
if len(addr_ieee) == 4:
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 330, in <module>
version = z.get_version_text()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 756, in get_version_text
v = self.get_version(refresh)['version']
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 287, in <module>
zigate.dispatcher.connect(callback_command, zigate.ZIGATE_DEVICE_NEED_REFRESH, z)
AttributeError: module 'zigate' has no attribute 'ZIGATE_DEVICE_NEED_REFRESH'
[2019-02-14 11:23:12][ERROR] : Impossible de lancer le démon zigate, relancer le démon en debug et vérifiez la log
[2019-02-14 10:24:41][ERROR][zigate](MainThread) : Failed to get network state
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 354, in need_discovery
if device.need_discovery():
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2627, in need_discovery
self.load_template()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2684, in load_template
self._bind_report()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2122, in _bind_report
self._zigate.bind_addr(self.addr, endpoint_id, 0x0006)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 952, in bind_addr
return self.bind(ieee, endpoint, cluster, dst_addr, dst_endpoint)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 940, in bind
dst_addr, dst_endpoint)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 924, in _bind_unbind
dst_addr_mode = self._choose_addr_mode(dst_addr)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 904, in _choose_addr_mode
if len(addr_ieee) == 4:
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 330, in <module>
version = z.get_version_text()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 756, in get_version_text
v = self.get_version(refresh)['version']
TypeError: 'NoneType' object is not subscriptable
[2019-02-14 10:25:18][ERROR][zigate](MainThread) : Failed to get network state
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 354, in need_discovery
if device.need_discovery():
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2627, in need_discovery
self.load_template()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2684, in load_template
self._bind_report()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2122, in _bind_report
self._zigate.bind_addr(self.addr, endpoint_id, 0x0006)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 952, in bind_addr
return self.bind(ieee, endpoint, cluster, dst_addr, dst_endpoint)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 940, in bind
dst_addr, dst_endpoint)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 924, in _bind_unbind
dst_addr_mode = self._choose_addr_mode(dst_addr)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 904, in _choose_addr_mode
if len(addr_ieee) == 4:
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 330, in <module>
version = z.get_version_text()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 756, in get_version_text
v = self.get_version(refresh)['version']
TypeError: 'NoneType' object is not subscriptable
[2019-02-14 10:26:28][ERROR][zigate](MainThread) : Failed to get network state
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 354, in need_discovery
if device.need_discovery():
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2627, in need_discovery
self.load_template()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2684, in load_template
self._bind_report()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2122, in _bind_report
self._zigate.bind_addr(self.addr, endpoint_id, 0x0006)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 952, in bind_addr
return self.bind(ieee, endpoint, cluster, dst_addr, dst_endpoint)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 940, in bind
dst_addr, dst_endpoint)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 924, in _bind_unbind
dst_addr_mode = self._choose_addr_mode(dst_addr)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 904, in _choose_addr_mode
if len(addr_ieee) == 4:
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 330, in <module>
version = z.get_version_text()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 756, in get_version_text
v = self.get_version(refresh)['version']
TypeError: 'NoneType' object is not subscriptable
[2019-02-14 10:27:29][ERROR][zigate](MainThread) : Failed to get network state
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 354, in need_discovery
if device.need_discovery():
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2627, in need_discovery
self.load_template()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2684, in load_template
self._bind_report()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2122, in _bind_report
self._zigate.bind_addr(self.addr, endpoint_id, 0x0006)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 952, in bind_addr
return self.bind(ieee, endpoint, cluster, dst_addr, dst_endpoint)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 940, in bind
dst_addr, dst_endpoint)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 924, in _bind_unbind
dst_addr_mode = self._choose_addr_mode(dst_addr)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 904, in _choose_addr_mode
if len(addr_ieee) == 4:
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 330, in <module>
version = z.get_version_text()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 756, in get_version_text
v = self.get_version(refresh)['version']
TypeError: 'NoneType' object is not subscriptable`
```
Merci.
Medou

**Comment by Medou31** [comment]
Bonjour,

Après avoir vu mon post passer en "closed" sans explications et qu'une version 1.2.2 était sortie, j'ai fait la mise à jour.
Or, j'ai toujours le même problème.
Le démon reste en statut NOK et je ne retrouve donc plus aucun de mes objets...

Pourriez-vous me dire quoi faire pour résoudre le problème (si je dois quoi faire) ou m'indiquer si c'est en cours de résolution pour une version 1.2.3 ?

Je vous remercie.
Cordialemetn,
Médou

Voici un screenshot du statut du plugin :
![image](https://user-images.githubusercontent.com/47629581/52858791-705cde80-312b-11e9-824f-f5677ee98b81.png)

Voici les logs que j'obtiens désormais lorsque je cherche à relancer le démon :
`[2019-02-15 14:02:28][INFO] : Lancement démon zigate : /usr/bin/python3 /var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py  --device /dev/ttyUSB0 --loglevel debug --apikey GjRxPICevM0yerEjOpanOVvlYCXaeu4H --pid /tmp/jeedom/zigate/daemon.pid --socket /tmp/jeedom/zigate/daemon.sock --callback http://127.0.0.1:80/plugins/zigate/core/php/jeeZiGate.php --sharedata 1
[2019-02-15 13:02:30][INFO][root](MainThread) : Start zigated
[2019-02-15 13:02:30][INFO][root](MainThread) : Log level : debug
[2019-02-15 13:02:30][INFO][root](MainThread) : Socket : /tmp/jeedom/zigate/daemon.sock
[2019-02-15 13:02:30][INFO][root](MainThread) : PID file : /tmp/jeedom/zigate/daemon.pid
[2019-02-15 13:02:30][INFO][root](MainThread) : Apikey : GjRxPICevM0yerEjOpanOVvlYCXaeu4H
[2019-02-15 13:02:30][INFO][root](MainThread) : Device : /dev/ttyUSB0
[2019-02-15 13:02:30][INFO][root](MainThread) : Callback : http://127.0.0.1:80/plugins/zigate/core/php/jeeZiGate.php
[2019-02-15 13:02:30][INFO][root](MainThread) : Python version : 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516]
[2019-02-15 13:02:30][INFO][root](MainThread) : zigate version : 0.27.9
[2019-02-15 13:02:30][DEBUG][root](MainThread) : Writing PID 21962 to /tmp/jeedom/zigate/daemon.pid
[2019-02-15 13:02:30][DEBUG][root](MainThread) : Send to test to jeedom
[2019-02-15 13:02:30][DEBUG][root](MainThread) : Send to jeedom :  {'action': 'test'}
[2019-02-15 13:02:30][DEBUG][requests.packages.urllib3.connectionpool](MainThread) : Starting new HTTP connection (1): 127.0.0.1
[2019-02-15 14:02:30][DEBUG] : Array (     [action] => test )
[2019-02-15 13:02:30][DEBUG][requests.packages.urllib3.connectionpool](MainThread) : http://127.0.0.1:80 "POST /plugins/zigate/core/php/jeeZiGate.php?apikey=GjRxPICevM0yerEjOpanOVvlYCXaeu4H HTTP/1.1" 200 16
[2019-02-15 13:02:30][DEBUG][root](MainThread) : Jeedom reply :  {'success': True}
[2019-02-15 13:02:30][INFO][root](MainThread) : D\xe9marrage ZiGate USB /dev/ttyUSB0
[2019-02-15 13:02:30][DEBUG][zigate](MainThread) : Try loading persistent file
[2019-02-15 13:02:30][DEBUG][zigate](MainThread) : Load success
[2019-02-15 13:02:30][DEBUG][zigate](MainThread) : REQUEST : 0x0010
[2019-02-15 13:02:30][DEBUG][zigate](MainThread) : Msg to send b'0010000010'
[2019-02-15 13:02:30][DEBUG][zigate](MainThread) : Encoded Msg to send b'01021010021002101003'
[2019-02-15 13:02:30][DEBUG][zigate](MainThread) : Waiting for status message for command 0x0010
[2019-02-15 14:02:32][INFO] : Démon zigate lancé
[2019-02-15 14:02:32][DEBUG] : Synchronisation des équipements entre le démon et jeedom
[2019-02-15 14:02:32][DEBUG] : callZiGate devices
[2019-02-15 13:02:33][WARNING][zigate](MainThread) : No response after command 0x0010 (1)
[2019-02-15 13:02:33][WARNING][zigate](MainThread) : Failed to retrieve zigate firmware version
[2019-02-15 13:02:33][DEBUG][zigate](MainThread) : REQUEST : 0x0021 b'\x03\x18\xc8\x00'
[2019-02-15 13:02:33][DEBUG][zigate](MainThread) : Msg to send b'00210004f60318c800'
[2019-02-15 13:02:33][DEBUG][zigate](MainThread) : Encoded Msg to send b'0102102102100214f6021318c8021003'
[2019-02-15 13:02:33][DEBUG][zigate](MainThread) : Waiting for status message for command 0x0021
[2019-02-15 13:02:36][WARNING][zigate](MainThread) : No response after command 0x0021 (2)
[2019-02-15 13:02:36][DEBUG][zigate](MainThread) : REQUEST : 0x0023 b'\x00'
[2019-02-15 13:02:36][DEBUG][zigate](MainThread) : Msg to send b'002300012200'
[2019-02-15 13:02:36][DEBUG][zigate](MainThread) : Encoded Msg to send b'010210230210021122021003'
[2019-02-15 13:02:36][DEBUG][zigate](MainThread) : Waiting for status message for command 0x0023
[2019-02-15 13:02:39][WARNING][zigate](MainThread) : No response after command 0x0023 (3)
[2019-02-15 13:02:39][DEBUG][zigate](MainThread) : Check network state
[2019-02-15 13:02:39][DEBUG][zigate](MainThread) : REQUEST : 0x0009
[2019-02-15 13:02:39][DEBUG][zigate](MainThread) : Msg to send b'0009000009'
[2019-02-15 13:02:39][DEBUG][zigate](MainThread) : Encoded Msg to send b'010210021902100210021903'
[2019-02-15 13:02:39][DEBUG][zigate](MainThread) : Waiting for status message for command 0x0009
[2019-02-15 13:02:42][WARNING][zigate](MainThread) : No response after command 0x0009 (4)
[2019-02-15 13:02:42][ERROR][zigate](MainThread) : Failed to get network state
[2019-02-15 13:02:42][DEBUG][zigate](MainThread) : Network is down, start it
[2019-02-15 13:02:42][DEBUG][zigate](MainThread) : REQUEST : 0x0024
[2019-02-15 13:02:42][DEBUG][zigate](MainThread) : Msg to send b'0024000024'
[2019-02-15 13:02:42][DEBUG][zigate](MainThread) : Encoded Msg to send b'01021024021002102403'
[2019-02-15 13:02:42][DEBUG][zigate](MainThread) : Waiting for status message for command 0x0024
[2019-02-15 13:02:45][WARNING][zigate](MainThread) : No response after command 0x0024 (5)
[2019-02-15 13:02:45][DEBUG][zigate](MainThread) : REQUEST : 0x0015
[2019-02-15 13:02:45][DEBUG][zigate](MainThread) : Msg to send b'0015000015'
[2019-02-15 13:02:45][DEBUG][zigate](MainThread) : Encoded Msg to send b'01021015021002101503'
[2019-02-15 13:02:45][DEBUG][zigate](MainThread) : Waiting for status message for command 0x0015
[2019-02-15 13:02:48][WARNING][zigate](MainThread) : No response after command 0x0015 (6)
[2019-02-15 13:02:48][DEBUG][zigate](Thread-2) : Check Need discovery LUMI lumi.weather (16bc) 00158d0002b56bc2
[2019-02-15 13:02:48][DEBUG][zigate](MainThread) : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/zigate.json
[2019-02-15 13:02:48][DEBUG][zigate](MainThread) : Saving persistent file
[2019-02-15 13:02:48][DEBUG][zigate](MainThread) : File already existing, make a backup before
[2019-02-15 13:02:48][DEBUG][zigate](Thread-2) : Check Need discovery LUMI lumi.weather (1aab) 00158d0002786c54
[2019-02-15 13:02:48][DEBUG][zigate](Thread-2) : Check Need discovery LUMI lumi.weather (e609) 00158d0002786a66
[2019-02-15 13:02:48][DEBUG][zigate](Thread-2) : Check Need discovery Philips LLC010 (1f93) 00178801001f2b24
[2019-02-15 13:02:48][WARNING][zigate](Thread-2) : No template found for LLC010
[2019-02-15 13:02:48][DEBUG][zigate](Thread-2) : Start automagic bind and report process for device Philips LLC010 (1f93) 00178801001f2b24
[2019-02-15 13:02:48][DEBUG][zigate](Thread-2) : Bind and report endpoint 242 for device Philips LLC010 (1f93) 00178801001f2b24
[2019-02-15 13:02:48][DEBUG][zigate](Thread-2) : Bind and report endpoint 11 for device Philips LLC010 (1f93) 00178801001f2b24
[2019-02-15 13:02:48][DEBUG][zigate](Thread-2) : bind and report for cluster 0x0006
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 354, in need_discovery
if device.need_discovery():
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2634, in need_discovery
self.load_template()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2691, in load_template
self._bind_report()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 2126, in _bind_report
self._zigate.bind_addr(self.addr, endpoint_id, 0x0006)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 956, in bind_addr
return self.bind(ieee, endpoint, cluster, dst_addr, dst_endpoint)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 944, in bind
dst_addr, dst_endpoint)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 928, in _bind_unbind
dst_addr_mode = self._choose_addr_mode(dst_addr)
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 908, in _choose_addr_mode
if len(addr_ieee) == 4:
TypeError: object of type 'NoneType' has no len()
[2019-02-15 13:02:48][DEBUG][zigate](MainThread) : REQUEST : 0x0010
[2019-02-15 13:02:48][DEBUG][zigate](MainThread) : Msg to send b'0010000010'
[2019-02-15 13:02:48][DEBUG][zigate](MainThread) : Encoded Msg to send b'01021010021002101003'
[2019-02-15 13:02:48][DEBUG][zigate](MainThread) : Waiting for status message for command 0x0010
[2019-02-15 13:02:51][WARNING][zigate](MainThread) : No response after command 0x0010 (7)
[2019-02-15 13:02:51][WARNING][zigate](MainThread) : Failed to retrieve zigate firmware version
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 330, in <module>
version = z.get_version_text()
File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 760, in get_version_text
v = self.get_version(refresh)['version']
TypeError: 'NoneType' object is not subscriptable
[2019-02-15 14:02:52][DEBUG] : result callZiGate
[2019-02-15 14:02:52][DEBUG] : Désactivation des équipements manquants
[2019-02-15 14:02:52][DEBUG] : callZiGate get_missing
[2019-02-15 14:02:52][DEBUG] : result callZiGate`

**Comment by doudz** [comment]
Il semblerait simplement que la clé ZiGate ne réponde pas
Est-elle bien branchée ?
La configuration du port est-elle bonne ?
Si vous avez mis à jour le firmware de la zigate récemment, avez-vous bien effacer la mémoire EEProm ?
Avez-vous essayer de débrancher /  rebrancher la cé ?

**Comment by Medou31** [comment]
Bonjour,

Merci pour ce retour rapide !
La clé est toujours bien branchée, je peux vérifier ce soir à nouveau, tout
comme essayer de la débrancher/rebrancher.

Je n'ai pas procédé à une mise à jour firmware depuis que je l'ai et je
n'ai pas changé la configuration du port.
Est-il possible qu'il soit modifié lors de la mise à jour du plugin ?

Cordialement,
Médou

**Comment by doudz** [comment]
Il peut arriver parfois, que la liaison USB ne fonctionne plus et que le port ait changé de nom tout seul

**Comment by Medou31** [comment]
Entendu, je vois.
Pour info, voici le choix que j'ai :
![image](https://user-images.githubusercontent.com/47629581/52861071-9f764e80-3131-11e9-83ff-c2b85b93dc4a.png)

Je suis configuré sur la ligne surlignée, cela devrait être bon non ? 
Désolé je suis encore assez candide avec la solution Jeedom...

**Comment by doudz** [comment]
Oui en principe c'est bon, mais essayez de débrancher et rebrancher la clé

**Comment by Medou31** [comment]
Après avoir débranché et rebranché ma clé, cela semble fonctionner.
Cependant j'ai perdu l'identification de tous mes objets... Ils semblent remonter mais sans leur identification... Cela devrait s'arranger si j'attends un peu plus ? (J'ai fait la manip il y a 5 minutes.)

J'ai eu un message me disant de mettre à jour le firmware de la clé. 
Je vais essayer de le faire mais j'avais galéré lorsque je l'ai reçue...
Pour faire la mise à jour du firmware, dois-je patienter un peu pour voir si les objets remontent correctement ?

Merci.

**Comment by doudz** [comment]
Quand vous dites identification, vous parlez du type ? Exemple lumi.sensor
Si c'est le cas :
- ce n'est pas normal, l'information est stocké dans un fichier donc soit vous avez supprimé le plugin (et donc le fichier) soit vous avez un problème de disque dur...
- L'info ne va pas revenir d'elle même, pour les équipements sur batterie, vous devez appuyer brievement sur le bouton d'appairage (pour xiaomi notamment), pour les équipements sur secteur vous pouvez utiliser la fonction découverte sur la page de l'équipement.

Vous n'êtes pas obligé de faire la mise à jour tout de suite

**Comment by Medou31** [comment]
Voici ce que je vois :
![image](https://user-images.githubusercontent.com/47629581/52882144-0e21cf00-3167-11e9-8170-6becf4fb6f22.png)

Je n''ai touché à aucun fichier ni supprimer le plugin. Le stockage est une carte SD placée sur un raspberry.

Evidemment (et heureusement pour l'instant), je n'ai pas beaucoup d'objets donc refaire la conf des équipements depuis zéro ne sera pas trop long mais c'est vraiment pénible !

N'ayant aucun changement après 10min j'ai lancé la mise à jour du firmware de la clé. 
La phase "Erase EEPROM" est d'ailleurs étrangement longue et comme il n'y a pas de bouton annuler j'ai laissé tourner. Je crains de mettre la clé en vrac en kickant le process...

Du coup j'attends, verdict en fin de soirée à mon avis.

**Comment by Medou31** [comment]
Hello,

J'ai enfin pu récupérer ma Zigate et le réseau.
Je rencontre cependant encore un problème :
- D'une part j'ai dû supprimer tous les objets pour les rajouter à nouveau. Je n'arrive pas faire ré-inclure ma Philips Hue Iris... Y-a-t-il une astuce pour l'inclure ? (La manipulation du bouton inclusion et brancher électriquement l'ampoule ne fonctionne pas....)

Merci

Médou

**Comment by doudz** [comment]
je pense qu'il faut faire un reset de l'ampoule, je ne connais pas la procédure

**Comment by Medou31** [comment]
Bonjour,

Je pense également mais après quelques recherches, je ne trouve que des procédures où il faut soit passer par le pont Philips (que je voudrais éviter d'utiliser vu que j'ai la clé Zigate ! et que je n'ai donc pas mis en oeuvre) soit utiliser un interrupteur Philips (que je n'ai pas).

J'ai fait un mail au support Philips mais je ne sais pas vraiment si cela va aboutir...
