### ISSUE TITLE
Daemon qui ne démarre pas

### ISSUE THREAD

**Issue by alexisfradel** [jeedom-zigate/jeedom-plugin-zigate#213]
Bonjour,

Je viens d'acheter un Raspberry Pi 4 et d'installer Jeedom en version 3.3.31 et le daemon du plugin ZiGate ne veut pas se lancer.

Si je met "Auto" dans le port je vois "Zigate not found" dans les logs et si je sélectionne manuellement le port /dev/ttyAMA0, j'ai le log suivant.

[2019-09-15 21:39:34][ERROR] : Attention je pense qu'il y a un soucis avec le démon que j'ai relancé plus de 3 fois consecutivement
[2019-09-15 21:39:34][INFO] : Lancement démon zigate : /usr/bin/python3 /var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py  --device /dev/ttyAMA0 --gpio 1 --loglevel debug --apikey hT94Dm2j0BpWgWwsQPy0mPj0iONdgKQy --pid /tmp/jeedom/zigate/daemon.pid --socket /tmp/jeedom/zigate/daemon.sock --callback http://127.0.0.1:80/plugins/zigate/core/php/jeeZiGate.php --sharedata 0
[2019-09-15 21:39:35][INFO][root](MainThread) : Start zigated
[2019-09-15 21:39:35][INFO][root](MainThread) : Log level : debug
[2019-09-15 21:39:35][INFO][root](MainThread) : Socket : /tmp/jeedom/zigate/daemon.sock
[2019-09-15 21:39:35][INFO][root](MainThread) : PID file : /tmp/jeedom/zigate/daemon.pid
[2019-09-15 21:39:35][INFO][root](MainThread) : Apikey : hT94Dm2j0BpWgWwsQPy0mPj0iONdgKQy
[2019-09-15 21:39:35][INFO][root](MainThread) : Device : /dev/ttyAMA0
[2019-09-15 21:39:35][INFO][root](MainThread) : Callback : http://127.0.0.1:80/plugins/zigate/core/php/jeeZiGate.php
[2019-09-15 21:39:35][INFO][root](MainThread) : Python version : 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.2.0]
[2019-09-15 21:39:35][INFO][root](MainThread) : zigate version : 0.32.2
[2019-09-15 21:39:35][DEBUG][root](MainThread) : Writing PID 7643 to /tmp/jeedom/zigate/daemon.pid
[2019-09-15 21:39:35][DEBUG][root](MainThread) : Send to test to jeedom
[2019-09-15 21:39:35][DEBUG][root](MainThread) : Send to jeedom :  {'action': 'test'}
[2019-09-15 21:39:35][DEBUG] : Array (     [action] => test )
[2019-09-15 21:39:35][DEBUG][root](MainThread) : Jeedom reply :  {'success': True}
[2019-09-15 21:39:35][INFO][root](MainThread) : Démarrage ZiGate /dev/ttyAMA0
/usr/local/lib/python3.7/dist-packages/zigate/core.py:2177: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
GPIO.setup(27, GPIO.OUT)  # GPIO2
[2019-09-15 21:39:36][DEBUG][zigate](MainThread) : Try loading persistent file
[2019-09-15 21:39:36][INFO] : Démon zigate lancé
[2019-09-15 21:39:36][DEBUG][zigate](MainThread) : Trying to load /var/www/html/plugins/zigate/core/class/../../resources/zigated/zigate.json
[2019-09-15 21:39:36][DEBUG][zigate](MainThread) : Load success
[2019-09-15 21:39:36][DEBUG][zigate](MainThread) : REQUEST : 0x0010
[2019-09-15 21:39:36][DEBUG][zigate](MainThread) : Msg to send b'0010000010'
[2019-09-15 21:39:36][DEBUG][zigate](MainThread) : Encoded Msg to send b'01021010021002101003'
[2019-09-15 21:39:36][DEBUG][zigate](MainThread) : Waiting for status message for command 0x0010
[2019-09-15 21:39:39][WARNING][zigate](MainThread) : No response after command 0x0010 (1)
[2019-09-15 21:39:39][WARNING][zigate](MainThread) : Failed to retrieve zigate firmware version
[2019-09-15 21:39:39][DEBUG][zigate](MainThread) : REQUEST : 0x0021 b'\x03\x18\xc8\x00'
[2019-09-15 21:39:39][DEBUG][zigate](MainThread) : Msg to send b'00210004f60318c800'
[2019-09-15 21:39:39][DEBUG][zigate](MainThread) : Encoded Msg to send b'0102102102100214f6021318c8021003'
[2019-09-15 21:39:39][DEBUG][zigate](MainThread) : Waiting for status message for command 0x0021
[2019-09-15 21:39:42][WARNING][zigate](MainThread) : No response after command 0x0021 (2)
[2019-09-15 21:39:42][DEBUG][zigate](MainThread) : REQUEST : 0x0023 b'\x00'
[2019-09-15 21:39:42][DEBUG][zigate](MainThread) : Msg to send b'002300012200'
[2019-09-15 21:39:42][DEBUG][zigate](MainThread) : Encoded Msg to send b'010210230210021122021003'
[2019-09-15 21:39:42][DEBUG][zigate](MainThread) : Waiting for status message for command 0x0023
[2019-09-15 21:39:45][WARNING][zigate](MainThread) : No response after command 0x0023 (3)
[2019-09-15 21:39:45][DEBUG][zigate](MainThread) : Check network state
[2019-09-15 21:39:45][DEBUG][zigate](MainThread) : REQUEST : 0x0009
[2019-09-15 21:39:45][DEBUG][zigate](MainThread) : Msg to send b'0009000009'
[2019-09-15 21:39:45][DEBUG][zigate](MainThread) : Encoded Msg to send b'010210021902100210021903'
[2019-09-15 21:39:45][DEBUG][zigate](MainThread) : Waiting for status message for command 0x0009
[2019-09-15 21:39:48][WARNING][zigate](MainThread) : No response after command 0x0009 (4)
[2019-09-15 21:39:48][ERROR][zigate](MainThread) : Failed to get network state
[2019-09-15 21:39:48][DEBUG][zigate](MainThread) : Network is down, start it
[2019-09-15 21:39:48][DEBUG][zigate](MainThread) : REQUEST : 0x0024
[2019-09-15 21:39:48][DEBUG][zigate](MainThread) : Msg to send b'0024000024'
[2019-09-15 21:39:48][DEBUG][zigate](MainThread) : Encoded Msg to send b'01021024021002102403'
[2019-09-15 21:39:48][DEBUG][zigate](MainThread) : Waiting for status message for command 0x0024
[2019-09-15 21:39:51][WARNING][zigate](MainThread) : No response after command 0x0024 (5)
[2019-09-15 21:39:51][DEBUG][zigate](MainThread) : REQUEST : 0x0015
[2019-09-15 21:39:51][DEBUG][zigate](MainThread) : Msg to send b'0015000015'
[2019-09-15 21:39:51][DEBUG][zigate](MainThread) : Encoded Msg to send b'01021015021002101503'
[2019-09-15 21:39:51][DEBUG][zigate](MainThread) : Waiting for status message for command 0x0015
[2019-09-15 21:39:54][WARNING][zigate](MainThread) : No response after command 0x0015 (6)
[2019-09-15 21:39:54][DEBUG][zigate](MainThread) : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/zigate.json
[2019-09-15 21:39:54][DEBUG][zigate](MainThread) : Saving persistent file
[2019-09-15 21:39:54][DEBUG][zigate](MainThread) : Acquire Lock to save persistent file
[2019-09-15 21:39:54][DEBUG][zigate](MainThread) : File already existing, make a backup before
[2019-09-15 21:39:54][DEBUG][zigate](MainThread) : Release Lock of persistent file
[2019-09-15 21:39:54][DEBUG][zigate](MainThread) : REQUEST : 0x0010
[2019-09-15 21:39:54][DEBUG][zigate](MainThread) : Msg to send b'0010000010'
[2019-09-15 21:39:54][DEBUG][zigate](MainThread) : Encoded Msg to send b'01021010021002101003'
[2019-09-15 21:39:54][DEBUG][zigate](MainThread) : Waiting for status message for command 0x0010
[2019-09-15 21:39:57][WARNING][zigate](MainThread) : No response after command 0x0010 (7)
[2019-09-15 21:39:57][DEBUG][zigate](MainThread) : REQUEST : 0x0010
[2019-09-15 21:39:57][DEBUG][zigate](MainThread) : Msg to send b'0010000010'
[2019-09-15 21:39:57][DEBUG][zigate](MainThread) : Encoded Msg to send b'01021010021002101003'
[2019-09-15 21:39:57][DEBUG][zigate](MainThread) : Waiting for status message for command 0x0010
[2019-09-15 21:40:00][WARNING][zigate](MainThread) : No response after command 0x0010 (8)
[2019-09-15 21:40:00][WARNING][zigate](MainThread) : Failed to retrieve zigate firmware version
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 332, in <module>
version = z.get_version_text()
File "/usr/local/lib/python3.7/dist-packages/zigate/core.py", line 805, in get_version_text
v = self.get_version(refresh)['version']
TypeError: 'NoneType' object is not subscriptable
[2019-09-15 21:40:03][ERROR] : Erreur sur la fonction deamon_start du plugin : Vous devez attendre au moins 45 secondes entre deux lancements du démon. Dernier lancement : 2019-09-15 21:39:34

Avez-vous une idée d'où pourrait venir le problème svp?
Merci pour votre aide.
Alexis

**Comment by doudz** [comment]
Je suis désolé je ne prends connaissance du problème que maintenant.
Si vous êtes toujours en attente d'une réponse, je vous suggère dans un premier temps d'utiliser Jeedom V4 afin d'avoir la dernière version du plugin

**Comment by doudz** [comment]
Je ferme par manque d'info
