### ISSUE TITLE
Le demon se lance quelques secondes puis repasse à NOK

### ISSUE THREAD

**Issue by vercoutt** [jeedom-zigate/jeedom-plugin-zigate#244]
**Description du bug**
Après installation du plugin, des dépendance et sélection du port, le demon se lance puis passe à NOK quelques secondes après.

voici le LOG :

[2020-01-09 14:13:03][ERROR][zigate](MainThread) : Failed to get network state
[2020-01-09 14:13:18][ERROR][zigate](MainThread) : Failed to start network
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 336, in <module>
if version < '3.0d':
TypeError: unorderable types: NoneType() < str()
[2020-01-09 14:15:22][ERROR][zigate](MainThread) : Failed to get network state
[2020-01-09 14:15:37][ERROR][zigate](MainThread) : Failed to start network
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 336, in <module>
if version < '3.0d':
TypeError: unorderable types: NoneType() < str()
[2020-01-09 14:20:23][ERROR][zigate](MainThread) : Failed to get network state
[2020-01-09 14:20:38][ERROR][zigate](MainThread) : Failed to start network
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 336, in <module>
if version < '3.0d':
TypeError: unorderable types: NoneType() < str()
[2020-01-09 14:25:21][ERROR][zigate](MainThread) : Failed to get network state
[2020-01-09 14:25:36][ERROR][zigate](MainThread) : Failed to start network
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 336, in <module>
if version < '3.0d':
TypeError: unorderable types: NoneType() < str()
[2020-01-09 14:27:34][ERROR][zigate](MainThread) : Failed to get network state
[2020-01-09 14:27:49][ERROR][zigate](MainThread) : Failed to start network
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 336, in <module>
if version < '3.0d':
TypeError: unorderable types: NoneType() < str()

**Screenshots**
Des captures d'écrans du problème (si applicable).

**Informations:**
- Type de l'équipement : Zigate GPIO (PiZigate)
- Version Jeedom : 4.0.38
- Version Plugin : 1.5.2 (2019-12-19 02:32:34)
- Version lib zigate : (impossible à savoir sans démarrage)
- Version du firmware : (impossible à savoir sans démarrage)

**Comment by doudz** [comment]
la clé ne semble pas communiquer, à tester avec la nouvelle version

**Comment by llaumgui** [comment]
Pas de réponse, je clos.
