### ISSUE TITLE
Plantage com avec Zigate Wifi

### ISSUE THREAD

**Issue by antfleu** [jeedom-zigate/jeedom-plugin-zigate#257]
Bonjour Doudz,

Depuis que j'ai mis à jour ton plugin en 1.6.4, je perds régulièrement la connexion avec ma Zigate (Wifi) et je dois redémarrer le démon pour reprendre la com avec mes modules. Je n'arrive pas à reproduire le problème, des fois il plante au bout d'une heure et des fois après 3-4-5 heures. 

J'ai mis le mode Debug et voila ce qu'il se passe avant de planter.

`[2020-03-28 14:01:06][DEBUG][zigate](Thread-94) : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/zigate.json
[2020-03-28 14:01:06][DEBUG][zigate](Thread-94) : Saving persistent file
[2020-03-28 14:01:06][DEBUG][zigate](Thread-94) : Acquire Lock to save persistent file
[2020-03-28 14:01:06][DEBUG][zigate](Thread-94) : Release Lock of persistent file
[2020-03-28 14:01:06][DEBUG][zigate](Thread-94) : REQUEST : 0x0010 
[2020-03-28 14:01:06][DEBUG][zigate](Thread-94) : Msg to send b'0010000010'
[2020-03-28 14:01:06][DEBUG][zigate](Thread-94) : Encoded Msg to send b'01021010021002101003'
[2020-03-28 14:01:06][DEBUG][zigate](Thread-94) : Waiting for status message for command 0x0010

> [2020-03-28 14:01:07][WARNING][zigate](ZiGate-Listen) : OOPS connection lost, reconnect...
> [2020-03-28 14:01:07][DEBUG][zigate](ZiGate-Listen) : ZiGate found on xxx.xxx.xxx.xxx port 9999

[2020-03-28 14:01:11][WARNING][zigate](Thread-94) : No response after command 0x0010 (1)
[2020-03-28 14:01:11][DEBUG][zigate](Thread-94) : ZiGate found on xxx.xxx.xxx.xxx port 9999
[2020-03-28 14:06:06][DEBUG][zigate](Thread-95) : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/zigate.json
[2020-03-28 14:06:06][DEBUG][zigate](Thread-95) : Saving persistent file
[2020-03-28 14:06:06][DEBUG][zigate](Thread-95) : Acquire Lock to save persistent file
[2020-03-28 14:06:06][DEBUG][zigate](Thread-95) : Release Lock of persistent file
[2020-03-28 14:06:06][DEBUG][zigate](Thread-95) : REQUEST : 0x0010 
[2020-03-28 14:06:06][DEBUG][zigate](Thread-95) : Msg to send b'0010000010'
[2020-03-28 14:06:06][DEBUG][zigate](Thread-95) : Encoded Msg to send b'01021010021002101003'
[2020-03-28 14:06:06][DEBUG][zigate](Thread-95) : Waiting for status message for command 0x0010
[2020-03-28 14:06:11][WARNING][zigate](Thread-95) : No response after command 0x0010 (2)

> Exception in thread ZiGate-Listen:
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/zigate/transport.py", line 339, in listen
>     read_sockets, write_sockets, error_sockets = select.select(socket_list, socket_list, [], 5)
> ValueError: file descriptor cannot be a negative integer (-1)

[2020-03-28 14:06:14][DEBUG][zigate](Thread-95) : ZiGate found on xxx.xxx.xxx.xxx port 9999
[2020-03-28 14:11:06][DEBUG][zigate](Thread-96) : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/zigate.json
[2020-03-28 14:11:06][DEBUG][zigate](Thread-96) : Saving persistent file
[2020-03-28 14:11:06][DEBUG][zigate](Thread-96) : Acquire Lock to save persistent file
[2020-03-28 14:11:06][DEBUG][zigate](Thread-96) : Release Lock of persistent file
[2020-03-28 14:11:06][DEBUG][zigate](Thread-96) : REQUEST : 0x0010 
[2020-03-28 14:11:06][DEBUG][zigate](Thread-96) : Msg to send b'0010000010'
[2020-03-28 14:11:06][DEBUG][zigate](Thread-96) : Encoded Msg to send b'01021010021002101003'
[2020-03-28 14:11:06][DEBUG][zigate](Thread-96) : Waiting for status message for command 0x0010
[2020-03-28 14:11:11][WARNING][zigate](Thread-96) : No response after command 0x0010 (3)
[2020-03-28 14:11:11][DEBUG][zigate](Thread-96) : ZiGate found on xxx.xxx.xxx.xxx port 9999
[2020-03-28 14:16:06][DEBUG][zigate](Thread-97) : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/zigate.json
[2020-03-28 14:16:06][DEBUG][zigate](Thread-97) : Saving persistent file
[2020-03-28 14:16:06][DEBUG][zigate](Thread-97) : Acquire Lock to save persistent file
[2020-03-28 14:16:06][DEBUG][zigate](Thread-97) : Release Lock of persistent file
[2020-03-28 14:16:06][DEBUG][zigate](Thread-97) : REQUEST : 0x0010 
[2020-03-28 14:16:06][DEBUG][zigate](Thread-97) : Msg to send b'0010000010'
[2020-03-28 14:16:06][DEBUG][zigate](Thread-97) : Encoded Msg to send b'01021010021002101003'
[2020-03-28 14:16:06][DEBUG][zigate](Thread-97) : Waiting for status message for command 0x0010
[2020-03-28 14:16:11][WARNING][zigate](Thread-97) : No response after command 0x0010 (4)
[2020-03-28 14:16:11][DEBUG][zigate](Thread-97) : ZiGate found on xxx.xxx.xxx.xxx port 9999
[2020-03-28 14:21:06][DEBUG][zigate](Thread-98) : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/zigate.json
[2020-03-28 14:21:06][DEBUG][zigate](Thread-98) : Saving persistent file
[2020-03-28 14:21:06][DEBUG][zigate](Thread-98) : Acquire Lock to save persistent file
[2020-03-28 14:21:06][DEBUG][zigate](Thread-98) : Release Lock of persistent file
[2020-03-28 14:21:06][DEBUG][zigate](Thread-98) : REQUEST : 0x0010 
[2020-03-28 14:21:06][DEBUG][zigate](Thread-98) : Msg to send b'0010000010'
[2020-03-28 14:21:06][DEBUG][zigate](Thread-98) : Encoded Msg to send b'01021010021002101003'
[2020-03-28 14:21:06][DEBUG][zigate](Thread-98) : Waiting for status message for command 0x0010
`
Je ne sais pas si la perte de connexion avec la Zigate est liée car à d'autres moments  elle se reconnecte sans problème.

`[2020-03-28 09:06:05][WARNING][zigate](ZiGate-Listen) : OOPS connection lost, reconnect...
[2020-03-28 09:06:05][DEBUG][zigate](ZiGate-Listen) : ZiGate found on xxx.xxx.xxx.xxx port 9999
[2020-03-28 09:06:10][WARNING][zigate](Thread-7) : No response after command 0x0010 (1)
[2020-03-28 09:06:10][DEBUG][zigate](Thread-7) : ZiGate found on xxx.xxx.xxx.xxx port 9999
[2020-03-28 09:09:33][DEBUG][zigate](ZiGate-Listen) : Raw packet received, b'\x01\x81\x02\x12\x02\x102\xa2\xca\xf6\xd5\x02\x11\x02\x10\x02\x10\xff\x02\x11\x02\x10B\x02\x10%\x02\x11!\xc7\x02\x1b\x02\x14!\xa8\x13\x02\x15!r\x02\x10\x02\x16$\x02\x11\x02\x10\x02\x10\x02\x10\x02\x10d)\xf0\x02\x17e!\xa7\x10f+\x02\x18|\x02\x11\x02\x10\x02\x1a!\x02\x10\x02\x10?\x03'
[2020-03-28 09:09:33][DEBUG][zigate](ZiGate-Event Loop) : Dispatch ZIGATE_PACKET_RECEIVED
[2020-03-28 09:09:33][DEBUG][zigate](ZiGate-Decode data) : Received response 0x8102: b'caf6d5010000ff01004200250121c70b0421a81305217200062401000000006429f0076521a710662b087c01000a210000'`

**Informations:**
- Type de l'équipement : Tous
- Version Jeedom : 4.0.45
- Version Plugin : 1.6.4
- Version lib zigate : 0.38.6
- Version du firmware : 3.1C Zigate Wifi

Merci

**Comment by antfleu** [comment]
J'ai enfin résolu/trouvé mon prob, c'était suite à une maj de mon routeur wifi.
Il y a eu une correction et c'est tout bon maintenant
