### ISSUE TITLE
Daemon redémarre et erreur lors de l'inclusion

### ISSUE THREAD

**Issue by jeromevdl** [Jeedom-Zigate/jeedom-plugin-zigate#64]
Je suis sur un raspberry (Linux raspberrypi 4.9.35-v7+), jeedom 3.2.11, Zigate 2018-08-30 22:27:54. 

L'installation s'est bien passée. Le démon a démarré, mais il redémarre très régulièrement (genre là à 22h25 puis 22h31 puis 22h34...) ou parfois s'arrête tout seul.

Je ne sais pas si c'est lié mais lorsque je veux me mettre en mode inclusion, j'ai direct une erreur et en regardant dans les logs, j'ai ça :

```
[2018-09-07 22:26:25][DEBUG] : callZiGate get_version_text
[2018-09-07 22:26:25][DEBUG] : result callZiGate
[2018-09-07 22:26:26][DEBUG] : callZiGate permit_join
[2018-09-07 22:26:26][DEBUG] : result callZiGate 
```

Les résultats semblent vides (probablement normal si je fais la requête lorsque le démon est down.

Sinon j'ai aussi ce log :

```
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
body=body, headers=headers)
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 304, in _make_request
self._validate_conn(conn)
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 724, in _validate_conn
conn.connect()
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 203, in connect
conn = self._new_conn()
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 133, in _new_conn
(self.host, self.port), self.timeout, **extra_kw)
File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 87, in create_connection
raise err
File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 78, in create_connection
sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/requests/adapters.py", line 362, in send
timeout=timeout
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
_pool=self, _stacktrace=stacktrace)
File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 245, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/lib/python3/dist-packages/six.py", line 624, in reraise
raise value.with_traceback(tb)
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
body=body, headers=headers)
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 304, in _make_request
self._validate_conn(conn)
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 724, in _validate_conn
conn.connect()
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 203, in connect
conn = self._new_conn()
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 133, in _new_conn
(self.host, self.port), self.timeout, **extra_kw)
File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 87, in create_connection
raise err
File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 78, in create_connection
sock.connect(sa)
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(110, 'Connection timed out'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 255, in <module>
if not jc.test():
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 71, in test
r = self.send_now({'action': 'test'})
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 67, in send_now
return self._request(message)
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 54, in _request
verify=False)
File "/usr/lib/python3/dist-packages/requests/api.py", line 94, in post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/lib/python3/dist-packages/requests/api.py", line 49, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 457, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 595, in send
history = [resp for resp in gen] if allow_redirects else []
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 595, in <listcomp>
history = [resp for resp in gen] if allow_redirects else []
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 189, in resolve_redirects
allow_redirects=False,
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 569, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python3/dist-packages/requests/adapters.py", line 407, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(110, 'Connection timed out'))
[2018-09-07 22:30:58][INFO] : Lancement démon zigate : /usr/bin/python3 /var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py  --device /dev/ttyUSB0 --loglevel debug --apikey ********************** --pid /tmp/jeedom/zigate/daemon.pid --socket /tmp/jeedom/zigate/daemon.sock --callback http://127.0.0.1:80/plugins/zigate/core/php/jeeZiGate.php --sharedata 1
[2018-09-07 22:30:59][INFO][root] : Start zigated
[2018-09-07 22:30:59][INFO][root] : Log level : debug
[2018-09-07 22:30:59][INFO][root] : Socket : /tmp/jeedom/zigate/daemon.sock
[2018-09-07 22:30:59][INFO][root] : PID file : /tmp/jeedom/zigate/daemon.pid
[2018-09-07 22:30:59][INFO][root] : Apikey : ***********************
[2018-09-07 22:30:59][INFO][root] : Device : /dev/ttyUSB0
[2018-09-07 22:30:59][INFO][root] : Callback : http://127.0.0.1:80/plugins/zigate/core/php/jeeZiGate.php
[2018-09-07 22:30:59][INFO][root] : Python version : 3.4.2 (default, Oct 19 2014, 13:31:11)
[GCC 4.9.1]
[2018-09-07 22:30:59][INFO][root] : zigate version : 0.19.1
[2018-09-07 22:30:59][DEBUG][root] : Writing PID 13484 to /tmp/jeedom/zigate/daemon.pid
[2018-09-07 22:30:59][DEBUG][root] : Send to test to jeedom
[2018-09-07 22:30:59][DEBUG][root] : Send to jeedom :  {'action': 'test'}
[2018-09-07 22:31:00][INFO] : Démon zigate lancé
```

Du coup, je ne peux pas faire grand chose... Une idée pour investiguer et avancer ?

Merci

**Comment by jeromevdl** [comment]
C'était en fait à cause d'un problème de config de mon réseau... par contre maintenant j'essaye de mettre à jour le firmware mais c'est un autre sujet...
