### ISSUE TITLE
Démarrage du Deamon impossible

### ISSUE THREAD

**Issue by icey74** [Jeedom-Zigate/jeedom-plugin-zigate#74]
Bonjour,

Première utilisation de ma ZIgate fraichement acquise, j'installe les dépendances sans problème, mais je n'arrive pas  a démarrer le deamon.

Il reste constamment à l'état NOK.

J'ai tenté de désactivé la gestion automatique mais pas de changement.
J'ai réinstallé le plugin, idem pas de changement.

J'ai toujours la même erreur dans les logs : 

```
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 147, in _new_conn
self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x75a22050>: Failed to establish a new connection: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
timeout=timeout
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
_stacktrace=sys.exc_info()[2])
File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 363, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /plugins/zigate/core/php/jeeZiGate.php?apikey=BY3snWhGFDtBhy3KfwP4E7SmpkXXRF7E (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x75a22050>: Failed to establish a new connection: [Errno 111] Connection refused',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):

```

Merci de votre aide

**Comment by llaumgui** [comment]
Ceci n'est pas un forum de support. Merci de poser vos questions sur le forums.

**Comment by doudz** [comment]
Si je peux me permettre, ceci ressemble à un crash, un issue me semble approprié

**Comment by llaumgui** [comment]
Un crash car le daemon ne se connecte pas à la lib. Comme c'est pas généralisé, je pense que le problème est sur le Jeedom et non dans le plugin.

**Comment by doudz** [comment]
oui c'est possible ou alors c'est une config particulière de Jeedom, mal géré par le plugin. il faudrait avoir le log entier pour savoir

**Comment by icey74** [comment]
Bonjour à vous, merci pour vos retours.

J'ai totalement réinstallé Jeedom avant de télécharger le plugin peut être que ai-je raté qqchose effectivement.

Je vais essayer de creuser côté configuration Jeedom et en attendant je vous pose la log complète ci-dessous : 

`[2018-10-29 01:14:03][INFO] : Lancement démon zigate : /usr/bin/python3 /var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py  --device /dev/ttyUSB0 --loglevel debug --apikey BY3snWhGFDtBhy3KfwP4E7SmpkXXRF7E --pid /tmp/jeedom/zigate/daemon.pid --socket /tmp/jeedom/zigate/daemon.sock --callback https://127.0.0.1:443/plugins/zigate/core/php/jeeZiGate.php --sharedata 0
[2018-10-29 00:14:04][INFO][root] : Start zigated
[2018-10-29 00:14:04][INFO][root] : Log level : debug
[2018-10-29 00:14:04][INFO][root] : Socket : /tmp/jeedom/zigate/daemon.sock
[2018-10-29 00:14:04][INFO][root] : PID file : /tmp/jeedom/zigate/daemon.pid
[2018-10-29 00:14:04][INFO][root] : Apikey : BY3snWhGFDtBhy3KfwP4E7SmpkXXRF7E
[2018-10-29 00:14:04][INFO][root] : Device : /dev/ttyUSB0
[2018-10-29 00:14:04][INFO][root] : Callback : https://127.0.0.1:443/plugins/zigate/core/php/jeeZiGate.php
[2018-10-29 00:14:04][INFO][root] : Python version : 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516]
[2018-10-29 00:14:04][INFO][root] : zigate version : 0.19.1
[2018-10-29 00:14:04][DEBUG][root] : Writing PID 9794 to /tmp/jeedom/zigate/daemon.pid
[2018-10-29 00:14:04][DEBUG][root] : Send to test to jeedom
[2018-10-29 00:14:04][DEBUG][root] : Send to jeedom :  {'action': 'test'}
[2018-10-29 00:14:04][DEBUG][requests.packages.urllib3.connectionpool] : Starting new HTTPS connection (1): 127.0.0.1
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 138, in _new_conn
(self.host, self.port), self.timeout, **extra_kw)
File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 98, in create_connection
raise err
File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 88, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
chunked=chunked)
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 350, in _make_request
self._validate_conn(conn)
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 837, in _validate_conn
conn.connect()
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 281, in connect
conn = self._new_conn()
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 147, in _new_conn
self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x75a22050>: Failed to establish a new connection: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
timeout=timeout
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
_stacktrace=sys.exc_info()[2])
File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 363, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /plugins/zigate/core/php/jeeZiGate.php?apikey=BY3snWhGFDtBhy3KfwP4E7SmpkXXRF7E (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x75a22050>: Failed to establish a new connection: [Errno 111] Connection refused',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 255, in <module>
if not jc.test():
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 71, in test
r = self.send_now({'action': 'test'})
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 67, in send_now
return self._request(message)
File "/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py", line 54, in _request
verify=False)
File "/usr/lib/python3/dist-packages/requests/api.py", line 110, in post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python3/dist-packages/requests/adapters.py", line 487, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /plugins/zigate/core/php/jeeZiGate.php?apikey=BY3snWhGFDtBhy3KfwP4E7SmpkXXRF7E (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x75a22050>: Failed to establish a new connection: [Errno 111] Connection refused',))
[2018-10-29 01:14:11][ERROR] : Impossible de lancer le démon zigate, relancer le démon en debug et vérifiez la log
`

**Comment by doudz** [comment]
C'est bon à savoir, à quel endroit est ce que le port avait été changé ?

**Comment by doudz** [comment]
Ok j'ai fait des essais, je confirme que c'est un problème de configuration de Jeedom.
La config réseau "Accès interne" a dû être modifié mais n'était sans doute pas valide.

Exemple :

![image](https://user-images.githubusercontent.com/1262548/47703419-87c99780-dc20-11e8-82e4-64451b9ce110.png)

Je clos.
