### ISSUE TITLE
Problème stabilité

### ISSUE THREAD

**Issue by ioull** [Jeedom-Zigate/jeedom-plugin-zigate#81]
Après une certaine période, le plugin ne recois plus de nouveaux evenements : 
Par exemple hier dernier message recu à 21:47 : 
[2018-11-03 21:41:07][DEBUG][zigate] : Received response 0x8102: b';\xd7\x82\x01\x00\x00\xff\x01\x00B\x00!\x01!\xb3\x0b\x03(\x11\x04!\xa8\x13\x05!\x07\x00\x06$\x01\x00\x00\x00\x00
!\x00\x00d\x10\x00\x0b!\x03\x00'
[2018-11-03 21:41:07][DEBUG][zigate] : RESPONSE 0x8102 - Individual Attribute Report : sequence:59, addr:d782, endpoint:1, cluster:0, attribute:65281, status:0, data_type:66, size:33, data:0121b30b0328110421a81305210700062401000000000a2100006410000b210300, rssi:108
[2018-11-03 21:41:07][DEBUG][zigate] : Dispatch ZIGATE_RESPONSE_RECEIVED
[2018-11-03 21:41:07][DEBUG][zigate] : Dispatch ZIGATE_ATTRIBUTE_UPDATED
[2018-11-03 21:41:07][DEBUG][root] : External command ZIGATE_ATTRIBUTE_UPDATED : {'zigate': <zigate.core.ZiGate object at 0x7f44ea9662b0>, 'attribute': {'endpoint': 1, 'data': '0121b30b0328110421a81305210700062401000000000a2100006410000b210300', 'cluster': 0, 'attribute': 65281, 'addr': 'd782', 'name': 'battery', 'value': 2.995, 'unit': 'V'}, 'device': Device d782 lumi.sensor_motion.aq2}
[2018-11-03 21:41:07][DEBUG][root] : Send to jeedom :  {'attribute': {'endpoint': 1, 'data': '0121b30b0328110421a81305210700062401000000000a2100006410000b210300', 'cluster': 0, 'attribute': 65281, 'addr': 'd782', 'name': 'battery', 'value': 2.995, 'unit': 'V'}, 'action': 'ZIGATE_ATTRIBUTE_UPDATED', 'device': Device d782 lumi.sensor_motion.aq2}
[2018-11-03 21:41:07][DEBUG][requests.packages.urllib3.connectionpool] : Starting new HTTP connection (1): 127.0.0.1
[2018-11-03 21:41:07][DEBUG] : Array (     [attribute] => Array         (             [endpoint] => 1             [data] => 0121b30b0328110421a81305210700062401000000000a2100006410000b210300             [cluster] => 0             [attribute] => 65281             [addr] => d782             [name] => battery             [value] => 2.995             [unit] => V         )      [action] => ZIGATE_ATTRIBUTE_UPDATED     [device] => Array         (             [info] => Array                 (                     [rssi] => 108                     [mac_capability] => 10000000                     [max_tx] => 100                     [bit_field] => 0100000000000010                     [addr] => d782                     [max_buffer] => 127                     [server_mask] => 0                     [manufacturer] => 1037                     [power_type] => 0                     [last_seen] => 2018-11-03 21:41:07                     [ieee] => 00158d0001b1cf93                     [id] => 7                     [max_rx] => 100                     [descriptor_capability] => 00000000                 )              [addr] => d782             [endpoints] => Array                 (                     [0] => Array                         (                             [in_clusters] => Array                                 (                                     [0] => 0                                     [1] => 65535                                     [2] => 1030                                     [3] => 1024                                     [4] => 1280                                     [5] => 1                                     [6] => 3                                 )                              [endpoint] => 1                             [device] => 263                             [profile] => 260                             [out_clusters] => Array                                 (                                     [0] => 0                                     [1] => 25                                 )                              [clusters] => Array                                 (                                     [0] => Array                                         (                                             [cluster] => 0                                             [attributes] => Array                                                 (                                                     [0] => Array                                                         (                                                             [name] => application_version                                                             [value] => 5                                                             [data] => 5                                                             [attribute] => 1                                                         )                                                      [1] => Array                                                         (                                                             [name] => type                                                             [value] => lumi.sensor_motion.aq2                                                             [data] => lumi.sensor_motion.aq2                                                             [attribute] => 5                                                         )                                                      [2] => Array                                                         (                                                             [data] => 0121b30b0328110421a81305210700062401000000000a2100006410000b210300                                                             [attribute] => 65281                                                             [name] => battery                                                             [value] => 2.995                                                             [unit] => V                                                         )                                                  )                                          )                                      [1] => Array                                         (                                             [cluster] => 1024                                             [attributes] => Array                                                 (                                                     [0] => Array                                                         (                                                             [data] => 28                                                             [attribute] => 0                                                             [name] => luminosity                                                             [value] => 28                                                             [unit] => lm                                                         )                                                  )                                          )                                      [2] => Array                                         (                                             [cluster] => 1030                                             [attributes] => Array                                                 (                                                     [0] => Array                                                         (                                                             [data] =>                                                              [attribute] => 0                                                             [name] => presence                                                             [value] =>                                                              [expire] => 10                                                         )                                                  )                                          )                                  )                          )                  )          )  )
[2018-11-03 21:41:07][DEBUG] : create command 1.0.65281
[2018-11-03 21:41:07][DEBUG][requests.packages.urllib3.connectionpool] : http://127.0.0.1:80 "POST /plugins/zigate/core/php/jeeZiGate.php?apikey=hHWPN5tmZPbDbHuIl8j6GSgcwR07xZrI HTTP/1.1" 200 16
[2018-11-03 21:41:07][DEBUG][root] : Jeedom reply :  {'success': True}
[2018-11-03 21:44:06][DEBUG][zigate] : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-11-03 21:49:06][DEBUG][zigate] : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-11-03 21:54:06][DEBUG][zigate] : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-11-03 21:59:06][DEBUG][zigate] : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-11-03 22:04:06][DEBUG][zigate] : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-11-03 22:09:06][DEBUG][zigate] : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-11-03 22:14:06][DEBUG][zigate] : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-11-03 22:19:06][DEBUG][zigate] : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-11-03 22:24:06][DEBUG][zigate] : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json

Par contre elle prends bien compte les commandes : 
On voit les reponses de la clef pour les versions et la non réponse de la commande off sur ma lumière philips qui s'est bien éteinte pourtant ...
[2018-11-04 09:35:10][DEBUG] : callZiGate get_version_text
[2018-11-04 09:35:10][DEBUG][root] : Message received in socket
[2018-11-04 09:35:10][DEBUG][root] : {'args': '', 'action': 'get_version_text'}
[2018-11-04 09:35:10][DEBUG][root] : {'success': True, 'result': '3.0d'}
[2018-11-04 09:35:10][DEBUG] : result callZiGate Array (     [success] => 1     [result] => 3.0d )
[2018-11-04 09:35:10][DEBUG] : callZiGate get_libversion
[2018-11-04 09:35:10][DEBUG][root] : Message received in socket
[2018-11-04 09:35:10][DEBUG][root] : {'args': '', 'action': 'get_libversion'}
[2018-11-04 09:35:10][DEBUG][root] : {'success': True, 'result': '0.20.2'}
[2018-11-04 09:35:10][DEBUG] : result callZiGate Array (     [success] => 1     [result] => 0.20.2 )
[2018-11-04 09:36:24][DEBUG] : callZiGate action_onoff Array (     [0] => 71e4     [1] => 11     [2] => 0 )
[2018-11-04 09:36:24][DEBUG][root] : Message received in socket
[2018-11-04 09:36:24][DEBUG][root] : {'args': ['71e4', 11, 0], 'action': 'action_onoff'}
[2018-11-04 09:36:24][DEBUG][zigate] : REQUEST : 0x0092 b'\x02q\xe4\x01\x0b\x00'
[2018-11-04 09:36:24][DEBUG][zigate] : Msg to send b'00920006090271e4010b00'
[2018-11-04 09:36:24][DEBUG][zigate] : Encoded Msg to send b'\x01\x02\x10\x92\x02\x10\x02\x16\x02\x19\x02\x12q\xe4\x02\x11\x02\x1b\x02\x10\x03'
[2018-11-04 09:36:24][DEBUG][zigate] : Waiting for status message for command 0x0092
[2018-11-04 09:36:27][ERROR][zigate] : No response after command 0x0092
[2018-11-04 09:36:27][DEBUG][root] : {'success': True, 'result': None}
[2018-11-04 09:36:27][DEBUG] : result callZiGate Array (     [success] => 1     [result] =>  )

Un petit redémarrage du démon et ca repart ... C'est comme si une tache de reception des messages étaient plantée ...

**Comment by doudz** [comment]
C'est possible mais je pense qu'on verrait un traceback dans le log.
Question bête, est-ce qu'il y a eu des évènements après 21h41 et 22h24 ? s'il ne s'est rien passé, il peut être normal que rien n'est été reçu.

**Comment by llaumgui** [comment]
Tu es en quel version ? Il y a eu des modifications sur le daemon. Du coup fallait le relancer sinon on pouvait avoir ce genre de pb. C'est général ou c'est réglé à présent ?

**Comment by ioull** [comment]
Non ce n'est pas réglé ... Malgré un gros try/catch qui aurait dû éviter
que la tâche réception des messages provenant de la librairie zigate ne
crash. Je pense donc effectivement a un crash côté librairie zigate mais
sans log :-(

Voici mes versions :
Version plugin  1.1.2-b4
Version lib  0.20.2
Version firmware  3.0d

Quand tu parles de redémarrer le démon, c'est celui de jeedom ? Je le
relance des que je vois que c'est crashé ...

**Comment by doudz** [comment]
C'est très ennuyeux...
Tous les logs sont bien en mode debug ?
Quand ça plante, est ce que tu vois une augmentation de l'utilisation du cpu?

**Comment by ioull** [comment]
Les logs du plugin zigate sont en mode début oui mais il y a d'autres log a
mettre en debug ?

Pas d'augmentation CPU non,.

Il faudrait que je copie la librairie zigate dans le plugin et ajouter des
logs dans la librairie pour voir ... Tu as une tâche qui tourne pour lire
le port série j'imagine ?

Le mer. 7 nov. 2018 à 12:33, Sébastien RAMAGE <notifications@github.com> a
écrit :

**Comment by llaumgui** [comment]
Maintenant que tu le dit je crois avoir déjà rencontré ça...

**Comment by doudz** [comment]
Il y 2 taches, une qui dialogue avec le port série et une qui traite les messages entrants 
ça peut être l'un ou l'autre, ou les 2...

**Comment by doudz** [comment]
Est-ce que c'est depuis que la librairie est passé en version 0.20 ? car cette version à apporter quelques petits bug...

**Comment by llaumgui** [comment]
Hier sur la sable.

**Comment by llaumgui** [comment]
Bonjour,

hier soir:
```
[2018-11-21 04:15:42][DEBUG][root] : External command ZIGATE_ATTRIBUTE_UPDATED : {'zigate': <zigate.core.ZiGate object at 0xffffa9fb1c18>, 'attribute': {'cluster': 1029, 'unit': '%', 'data': 9438, 'value': 94.38, 'attribute': 0, 'endpoint': 1, 'name': 'humidity', 'addr': '3319'}, 'device': Device 3319 lumi.weather}
Exception in thread Thread-3:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.5/dist-packages/zigate/transport.py", line 93, in listen
self.read_data(data)
File "/usr/local/lib/python3.5/dist-packages/zigate/transport.py", line 80, in read_data
threading.Thread(target=self.packet_received, args=(raw_message,)).start()
File "/usr/lib/python3.5/threading.py", line 844, in start
_start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```
Et du coup même symptome que @ioull 
Pour moi le problème est dans la lib ?

**Comment by ioull** [comment]
Ce qui est bizarre c'est que j'ai pas de stacktrace moi ...
Par contre pour tester un patch, je suis champion, ca tombe environ 1 fois
par jour ;-)

**Comment by doudz** [comment]
Le message est clair, impossible de démarrer un nouveau Thread.
Cela arrive lorsqu'on atteint les limites de capacités du système.
Je vais chercher de mon côté

**Comment by llaumgui** [comment]
Oui, je sais mais j'ai rien eu a cette heure... Après ma charge et mon CPU sont pas déconnant sur ce créneau.

**Comment by doudz** [comment]
Eventuellement il faudrait faire un `ps -othcount <PID>` en indiquant le PID du démon pour voir ce qui cloche
Eventuellement surveiller pendant un moment `watch ps -othcount <PID>`

**Comment by ioull** [comment]
J'ai le plugin en panne depuis 2h du mat, je peux faire des tests si vous
voulez :
vinz@myjeedom:/var/www/html/plugins/zigate/resources/zigated/zigate.old$ ps
-ef |grep zigate
www-data 28062     1  0 nov.20 ?       00:12:25 /usr/bin/python3
/var/www/html/plugins/zigate/core/class/../../resources/zigated/zigated.py
--device auto --loglevel debug --apikey hHWPN5tmZPbDbHuIl8j6GSgcwR07xZrI
--pid /tmp/jeedom/zigate/daemon.pid --socket /tmp/jeedom/zigate/daemon.sock
--callback http://127.0.0.1:80/plugins/zigate/core/php/jeeZiGate.php
--sharedata 1
vinz     31199 28650  0 14:57 pts/0    00:00:00 grep zigate
vinz@myjeedom:/var/www/html/plugins/zigate/resources/zigated/zigate.old$ ps
-othcount 28062
THCNT
    6

**Comment by llaumgui** [comment]
Après je veux bien qu'a un moment il y ai un peu moins de puissance dispo, mais d'autre daemon ne plante pas...

**Comment by llaumgui** [comment]
OK, déjà je vais passer ton PR en dev voir beta.

**Comment by ioull** [comment]
Je peux fournir les logs en debug complete ... Mais vous avez l'extrait
dans le premier post ... Je n'ai pas d'information supplementaire même si
j'ai essayé d'ajouter des logs dans la librairie et dans le plugin ...

Si vous avez une librairie plus verbeuse ou m'aiguiller dans quel thread se
mettre je peux en ajouter !!!

Au repos le nombre de thread chez moi est bien 6. En ce moment en tout cas
il est à 6 et je recois bien les infos de la clef.

**Comment by doudz** [comment]
ok, donc au repos c'est donc 6 (j'ai oublié de compter la sauvegarde automatique)
il n'y a donc rien de bloquer.
@ioull tu as quel firmware ? 3.0d ou 3.0e ?

**Comment by ioull** [comment]
toujours en 3.0d, le plugin n'est pas encore compatible 3.0e il me semble ?
Je peux faire les changements car ce n'est pas en production pour moi ;-)

**Comment by doudz** [comment]
Pour le 3.0e il faut utiliser la lib python 0.21.2

**Comment by ioull** [comment]
ET pas besoin de changement dans le plugin ?

**Comment by doudz** [comment]
Non pas d'autres changements que la version de la lib zigate

**Comment by llaumgui** [comment]
C'est mieux depuis a MAJ de la version de la lib ?

**Comment by ioull** [comment]
Non pas pour moi ... planté à 22h15 cette nuit :-(

**Comment by doudz** [comment]
Rien dans le log ?
Tu fonctionnes sur quoi ?
J'ai déjà eu ce genre de bizarrerie sur mon RPI quand la carte SD commence à mourrir

**Comment by doudz** [comment]
ah on est sur une machine virtuelle, on tient une piste, est-ce que ça sera pas la machine virtuelle qui ferme la redirection de port USB au bout d'un moment ?

**Comment by ioull** [comment]
Non je ne crois pas que ce soit un problème de deconnexion de port USB
puisque je n'ai rien dans les logs de proxmox vers ces heures ci, c'était
ma première idée ... l'envoi de commande continue de marcher donc le port
USB est bein vue de la VM ...

Par contre si on peut mettre des logs autour de la reception USB et/ou de
la deconnexion de port je suis prenneur.

Pour info, dans ma VM, j'ai également une clef zwave et un boitier rfxcom
qui ne présente pas ces problèmes de taches HS.

    Vincent.

Le lun. 3 déc. 2018 à 20:33, Sébastien RAMAGE <notifications@github.com> a
écrit :

**Comment by doudz** [comment]
> [2018-12-02 21:43:37][DEBUG] : create command 1.1027.16

Il se passe quoi dans le log avant cette ligne ?

**Comment by ioull** [comment]
Désolé pour ma non réactivité mais j'ai du attendre que ca se reproduise
car je n'avais plus les logs ...
[2018-12-04 21:18:42][DEBUG][zigate] : Dispatch ZIGATE_PACKET_RECEIVED
[2018-12-04 21:18:42][DEBUG][zigate] : Received response 0x8102:
b'238997010402000000290002060b'
[2018-12-04 21:18:42][DEBUG][zigate] : RESPONSE 0x8102 - Individual
Attribute Report : sequence:35, addr:8997, endpoint:1, cluster:1026,
attribute:0, status:0, data_type:41, size:2, data:1547, rssi:72
[2018-12-04 21:18:42][DEBUG][zigate] : Dispatch ZIGATE_RESPONSE_RECEIVED
[2018-12-04 21:18:42][DEBUG][zigate] : Dispatch ZIGATE_ATTRIBUTE_UPDATED
[2018-12-04 21:18:42][DEBUG][root] : External command
ZIGATE_ATTRIBUTE_UPDATED : {'attribute': {'value': 15.47, 'data': 1547,
'addr': '8997', 'cluster': 1026
, 'name': 'temperature', 'attribute': 0, 'unit': '°C', 'endpoint': 1},
'zigate': <zigate.core.ZiGate object at 0x7f52287372b0>, 'device': Device
00158d0001dbd5f3 (8997) }
[2018-12-04 21:18:42][DEBUG][root] : Send to jeedom :  {'action':
'ZIGATE_ATTRIBUTE_UPDATED', 'attribute': {'value': 15.47, 'data': 1547,
'addr': '8997', 'cluster': 1026, 'name': 'temperature', 'attribute': 0,
'unit': '°C', 'endpoint': 1}, 'device': Device 00158d0001dbd5f3 (8997) }
[2018-12-04 21:18:42][DEBUG][requests.packages.urllib3.connectionpool] :
Starting new HTTP connection (1): 127.0.0.1
[2018-12-04 21:18:42][DEBUG] : Array (     [action] =>
ZIGATE_ATTRIBUTE_UPDATED     [attribute] => Array         (
 [value] => 15.47             [data] => 1547             [addr] => 8997
         [cluster] => 1026             [name] => temperature
 [attribute] => 0             [unit] => °C             [endpoint] => 1
   )      [device] => Array         (             [info] => Array
       (                     [id] => 3                     [rssi] => 72
                 [addr] => 8997                     [power_type] => 0
               [last_seen] => 2018-12-04 21:18:42
 [ieee] => 00158d0001dbd5f3                 )              [endpoints] =>
Array                 (                     [0] => Array
     (                             [device] => 0
 [clusters] => Array                                 (
               [0] => Array                                         (
                                       [attributes] => Array
                                 (
           [0] => Array
     (                                                             [value]
=> 2.985                                                             [data]
=>
0121a90b0421a81305210d0006240100000000642914066521511c662bd38601000a210000
                                                           [name] =>
battery
 [attribute] => 65281
       [unit] => V
 )                                                  )
                        [cluster] => 0
   )                                      [1] => Array
                   (
 [attributes] => Array                                                 (
                                                 [0] => Array
                                           (
                             [value] => 15.47
                               [data] => 1547
                               [name] => temperature
                                     [attribute] => 0
                                       [unit] => °C
                                 )
        )                                              [cluster] => 1026
                                     )
[2] => Array                                         (
                       [attributes] => Array
                 (                                                     [0]
=> Array                                                         (
                                                   [value] => 1000
                                                   [data] => 1000
                                                   [name] => pressure
                                                       [attribute] => 0
                                                         [unit] => mb
                                                   )
                              [1] => Array
                       (
         [value] => 1000.5
           [data] => 10005
           [name] => pressure2
               [attribute] => 16
                 [unit] => mb
           )                                                      [2] =>
Array                                                         (
                                                 [attribute] => 20
                                                   [data] => -1
                                             )
                    )
[cluster] => 1027                                         )
                      [3] => Array
 (                                             [attributes] => Array
                                         (
                   [0] => Array
             (
 [value] => 73.28
   [data] => 7328
   [name] => humidity
       [attribute] => 0
         [unit] => %
 )                                                  )
                        [cluster] => 1029
       )                                  )
[profile] => 0                             [out_clusters] => Array
                       (                                 )
            [in_clusters] => Array                                 (
                         )                              [endpoint] => 1
                     )                  )              [addr] => 8997
   )  )
[2018-12-04 21:18:42][DEBUG] : create command 1.1026.0
[2018-12-04 21:18:42][DEBUG][requests.packages.urllib3.connectionpool] :
http://127.0.0.1:80 "POST
/plugins/zigate/core/php/jeeZiGate.php?apikey=hHWPN5tmZPbDbHuIl8j6GSgcwR07xZrI
HTTP/1.1" 200 16
[2018-12-04 21:18:42][DEBUG][root] : Jeedom reply :  {'success': True}
[2018-12-04 21:20:24][DEBUG][zigate] : Auto saving
/var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-12-04 21:20:24][DEBUG][zigate] : Saving persistent file
[2018-12-04 21:20:24][DEBUG][zigate] : File already existing, make a backup
before
[2018-12-04 21:25:24][DEBUG][zigate] : Auto saving
/var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-12-04 21:25:24][DEBUG][zigate] : Saving persistent file
[2018-12-04 21:25:24][DEBUG][zigate] : File already existing, make a backup
before
[2018-12-04 21:30:24][DEBUG][zigate] : Auto saving
/var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-12-04 21:30:24][DEBUG][zigate] : Saving persistent file
[2018-12-04 21:30:24][DEBUG][zigate] : File already existing, make a backup
before
[2018-12-04 21:35:24][DEBUG][zigate] : Auto saving
/var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-12-04 21:35:24][DEBUG][zigate] : Saving persistent file
[2018-12-04 21:35:24][DEBUG][zigate] : File already existing, make a backup
before
[2018-12-04 21:40:24][DEBUG][zigate] : Auto saving
/var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-12-04 21:40:24][DEBUG][zigate] : Saving persistent file
[2018-12-04 21:40:24][DEBUG][zigate] : File already existing, make a backup
before
[2018-12-04 21:45:24][DEBUG][zigate] : Auto saving
/var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-12-04 21:45:24][DEBUG][zigate] : Saving persistent file
[2018-12-04 21:45:24][DEBUG][zigate] : File already existing, make a backup
before

**Comment by doudz** [comment]
Merci pour le log, effectivement rien d'anormal...
et dans le log http.error, rien non plus ?

Par ailleurs, ça se produit toujours après 21H non ? yaurait pas autre chose qui se lance à ce moment là ?

**Comment by CaiRve** [comment]
Salut,

J'ai exactement le meme pb !!!
au moins une fois par jour 
`[2018-12-13 07:00:44][DEBUG][zigate] : Dispatch ZIGATE_ATTRIBUTE_UPDATED
[2018-12-13 07:00:44][DEBUG][root] : External command ZIGATE_ATTRIBUTE_UPDATED : {'device': Device 00158d0001e52d33 (fbaa) lumi.sensor_motion.aq2, 'attribute': {'endpoint': 1, 'addr': 'fbaa', 'value': 24, 'name': 'luminosity', 'unit': 'lm', 'data': 24, 'cluster': 1024, 'attribute': 0}, 'zigate': <zigate.core.ZiGate object at 0x76317250>}
[2018-12-13 07:00:44][DEBUG][zigate] : Dispatch ZIGATE_PACKET_RECEIVED
Exception in thread ZiGate-Event Loop:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 156, in _event_loop
    self.decode_data(packet)
  File "/usr/local/lib/python3.5/dist-packages/zigate/core.py", line 377, in decode_data
    struct.unpack('!HHB%dsB' % (len(decoded) - 6), decoded)
struct.error: bad char in struct format

[2018-12-13 07:00:44][DEBUG][root] : Send to jeedom :  {'device': Device 00158d0001e52d33 (fbaa) lumi.sensor_motion.aq2, 'attribute': {'endpoint': 1, 'addr': 'fbaa', 'value': 24, 'name': 'luminosity', 'unit': 'lm', 'data': 24, 'cluster': 1024, 'attribute': 0}, 'action': 'ZIGATE_ATTRIBUTE_UPDATED'}
[2018-12-13 07:00:44][DEBUG][requests.packages.urllib3.connectionpool] : Starting new HTTP connection (1): 127.0.0.1
[2018-12-13 07:00:44][DEBUG][requests.packages.urllib3.connectionpool] : http://127.0.0.1:8099 "POST /plugins/zigate/core/php/jeeZiGate.php?apikey=cJiweZMYvV5cY1I8biMlEF5k4iAnE9eM HTTP/1.1" 200 16
[2018-12-13 07:00:44][DEBUG][root] : Jeedom reply :  {'success': True}
[2018-12-13 07:02:19][DEBUG][zigate] : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-12-13 07:02:19][DEBUG][zigate] : Saving persistent file
[2018-12-13 07:02:19][DEBUG][zigate] : File already existing, make a backup before
[2018-12-13 07:07:19][DEBUG][zigate] : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-12-13 07:07:19][DEBUG][zigate] : Saving persistent file
[2018-12-13 07:07:19][DEBUG][zigate] : File already existing, make a backup before
[2018-12-13 07:12:19][DEBUG][zigate] : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-12-13 07:12:19][DEBUG][zigate] : Saving persistent file
[2018-12-13 07:12:19][DEBUG][zigate] : File already existing, make a backup before
[2018-12-13 07:17:20][DEBUG][zigate] : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-12-13 07:17:20][DEBUG][zigate] : Saving persistent file
[2018-12-13 07:17:20][DEBUG][zigate] : File already existing, make a backup before
[2018-12-13 07:22:20][DEBUG][zigate] : Auto saving /var/www/html/plugins/zigate/core/class/../../resources/zigated/.zigate.json
[2018-12-13 07:22:20][DEBUG][zigate] : Saving persistent file
`

je suis obligé de faire une restart du démon pour que cela refonctionne ....

**Comment by doudz** [comment]
Aaah là on a un traceback ,merci @CaiRve on avance

**Comment by CaiRve** [comment]
de rien
je suis sur rpi3, la clé est sur un hub usb, et a priori pas de soucis de puissance

**Comment by doudz** [comment]
Donc a priori c'est un problème de décodage de paquet. c'est pas supposé arriver, ça veut dire que la zigate a envoyé un message incompréhensible
@CaiRve est-ce que tu serais en mesure de modifier un fichier pour faire un essai ? (comme le problème arrive souvent chez toi)
Si oui il faudrait modifier le fichier `/usr/local/lib/python3.5/dist-packages/zigate/core.py`
avant la ligne 375 ajouter `LOGGER.debug('Packet: {}'.format(hexlify(packet)))`
ça donnerait ça :
```
...
def decode_data(self, packet):
        '''
        Decode raw packet message
        '''
        LOGGER.debug('Packet: {}'.format(hexlify(packet)))
        decoded = self.zigate_decode(packet[1:-1])
...
```
ça va pas résoudre le problème mais c'est pour comprendre ce qu'il se passe

**Comment by doudz** [comment]
@ioull j'ai apporté une modification pour afficher un message d'erreur à la place d'un plantage (si c'est bien ça le problème)

**Comment by CaiRve** [comment]
j'ai eu un peu de mal a le faire redémarrer, au lieu d'espaces j'avais mis un tabulation, il avait pas aimé :-D
Bon , en attente du prochain plantage.

**Comment by doudz** [comment]
Je pense que je commence à comprendre ce qu'il se passe, je crois que c'est vraiment un problème de communication entre la zigate et le système, à cause d'un HUB usb ou d'un mauvais câble, etc.
Chaque message est fait comme ça : **Début** + **Message** + **Fin**
Dans le cas de @CaiRve , il y a bien un **Début** et une **Fin** mais le message est incohérent d'où le plantage.
Dans le cas de @ioull , je pense qu'il manque le **Début** d'un message, du coup le système reçoit probablement la suite et sans doute d'autres messages mais comme il manque le début il ne traite plus ce qui arrive.
Je vais faire des essais dans ce sens et gérer ces cas particuliers.

**Comment by doudz** [comment]
Je pensais avoir résolu le problème, mais il vient de se produire chez moi... 
Je vais continuer à chercher

**Comment by CaiRve** [comment]
OK, au moins chez toi aussi cela peut arriver, ca me rassure ^^
en tout cas, de mon coté, le soucis ne s'est plus reproduit ...

**Comment by doudz** [comment]
Je pense avoir trouver la source du problème.
J'ai mis à jour la lib (0.24.2) afin de produire une erreur dans le log à la place d'un plantage silencieux

**Comment by llaumgui** [comment]
@doudz > Possible de le mettre sur la version actuelle ? Car j'ai vu ça dans ton changelog:

>  WARNING this is a breaking change for read_attribute_request, write_attribute_request, reporting_request

**Comment by doudz** [comment]
Oui, de mémoire c'est pas utilisé côté plugin

**Comment by Flowent** [comment]
Bonjour a tous... Je ne sais pas si j'ai le même problème... Mais de temps en temps, plus aucune commande ne fonctionne (par exemple j'appuie sur un bouton qui lance normalement un scénario... Mais rien)... Pas de log, même en débug.. juste .. rien.....  Et tout est ok...

Je redémarre le démon et la toutes mes commandes se lancent a la suite comme si il attendait qqchose et que le redémarrage a débloquer qqchose....

En attendant j'ai un scénario qui relance le démon toutes les 3h... Pas terrible...

Merci de votre aide

**Comment by ioull** [comment]
Ca resssemble à mon problème ... Je l'ai résolu en enlevant ma rallonge usb
sur laquelle était la zigate ... et depuis plus de problème ... Il faut que
je la remette pour voir si la nouvelle librairie a fixé le problème comme
annoncé par doudz

En attendant j'avais mis un script qui se lancait toutes les 5 minutes pour
redemarrer le plugin seulement si il avait pas recu de nouvelle des
capteurs depuis plus de 30 minutes

// Équipements catégorie security
$cat = eqLogic::ByType('zigate');

//On récupère les équipements de la catégorie security
foreach($cat as $i){
//On récupère le nom entier de l'équipement
    $human = $i->getHumanName();
    $lastDeviceCommunication = $i->getStatus('lastCommunication');

    if( $lastDeviceCommunication > $lastCommunication) {
    $lastCommunication = $lastDeviceCommunication;
    }

    $scenario->setLog($human . '=>' . $lastDeviceCommunication . '/' .
$lastCommunication);
}

if ($lastCommunication < date('Y-m-d H:i:s', strtotime('-30 minutes' .
date('Y-m-d H:i:s')))) {
    message::add('Zigate', 'Reboot ...');
    $scenario->setLog('**** ERROR LastCommunication : ' .
$lastCommunication . '>' . date('Y-m-d H:i:s', strtotime('-30 minutes' .
date('Y-m-d H:i:s'))));
    zigate::deamon_start();
}


//**********************************************************
// Set variable for the next steps of the scenario
//**********************************************************
//$scenario->setData("zWave_ModuleError_Battery", implode(',',
$Error_Module_Battery));
//$scenario->setData("zWave_ModuleError_Sector", implode(',',
$Error_Module_Sector));

$scenario->setLog('**********************************************************');
$scenario->setLog('***** Fin *****');
$scenario->setLog('**********************************************************');
//**********************************************************

**Comment by doudz** [comment]
Est-ce toujours d'actualité ? sinon je clôture le ticket

**Comment by Flowent** [comment]
De mon coté, brancher la Zigate directement sur la box (sans passer par un hub) a résolu le problème
