### ISSUE TITLE
Problème lors de l'installation des dépendances sur Debian Jessie

### ISSUE THREAD

**Issue by f-l-s** [Jeedom-Zigate/jeedom-plugin-zigate#98]
Bonjour, 
Une exception est levée lors de l'installation des dépendances.
Voici la log.
[zigate_update.txt](https://github.com/Jeedom-Zigate/jeedom-plugin-zigate/files/2715723/zigate_update.txt)

Les versions n'apparaissent pas dans la log, mais les voici :
Version Jeedom 3.0
Version plugin 1.1.5 (2018-12-25 02:15:17)

Sauriez-vous d'où ça vient svp ?
Merci. :)

**Comment by llaumgui** [comment]
C'est quoi ta version de debian et de pip ?

**Comment by f-l-s** [comment]
Celle installée initialement par Jeedom sur ma Mini+ et updatée via le système de mise à jour.
Je viens de me connecter en SSH, il s'agit de la Debian 8.3.
Pour pip, quand je lance la commande "which pip", j'ai "/usr/bin/pip".
Mais si je lance la commande "pip -V" ou "pip quelqueChose", il ne se passe rien. Un ctrl+c me donne l'erreur suivante :
`jeedom@jeedom:~$ pip -V


^CTraceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 22, in <module>
    import requests, six
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 68, in <module>
    _attach_namespace(urllib3, 'requests.packages')
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 63, in _attach_namespace
    module = __import__(name)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 55, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 4, in <module>
    binding = Binding()
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in __init__
    self._ensure_ffi_initialized()
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 113, in _ensure_ffi_initialized
    libraries=libraries,
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/utils.py", line 57, in build_ffi
    ffi.cdef("\n".join(cdef_sources))
  File "/usr/lib/python2.7/dist-packages/cffi/api.py", line 103, in cdef
    self._parser.parse(csource, override=override, packed=packed)
  File "/usr/lib/python2.7/dist-packages/cffi/cparser.py", line 166, in parse
    self._internal_parse(csource)
  File "/usr/lib/python2.7/dist-packages/cffi/cparser.py", line 172, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/usr/lib/python2.7/dist-packages/cffi/cparser.py", line 127, in _parse
    ast = _get_parser().parse(csource)
  File "/usr/lib/python2.7/dist-packages/pycparser/c_parser.py", line 138, in parse
    debug=debuglevel)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 269, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 975, in parseopt_notrack
    p.callable(pslice)
  File "/usr/lib/python2.7/dist-packages/pycparser/c_parser.py", line 767, in p_init_declarator
    p[0] = dict(decl=p[1], init=(p[3] if len(p) > 2 else None))
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 206, in __setitem__
    self.slice[n].value = v
KeyboardInterrupt`

**Comment by doudz** [comment]
De mémoire il faudrait être au moins en version 9 ou 10
Pour vérifier
pip3 -V

ou python3 -m pip -V

**Comment by doudz** [comment]
@llaumgui vu la tournure que ça prend je crois qu'on va se passer de pip et inclure la lib python directement dans le plugin
Ainsi les dépendances seront plus stables et on perturbera pas le développeur grincheux

**Comment by f-l-s** [comment]
@llaumgui et @doudz
Merci beaucoup pour votre réactivité (et aussi pour votre implication dans ce plugin ! :) )
Mon installation est dû pur Jeedom : Jeedom Mini+. Je laisse donc l’équipe Jeedom gérer les updates d’OS et autres libs core pour continuer à bénéficier de leur support et éviter tout problème ultérieur.

Ce problème est-il propre aux Jeedom Mini ?

Ps : “Developpeur grincheux”, je n’ai pas compris ?

**Comment by doudz** [comment]
On va modifier le plugin pour palier au problème.

Pour le développeur grincheux, c'est une private joke, on a eu un petit conflit avec Lunarok pour ne pas le citer

**Comment by llaumgui** [comment]
Zut elle est lts la Jessie... Pas moyen de faire une syntaxe sans wildcard ?

**Comment by llaumgui** [comment]
https://stackoverflow.com/questions/5226311/installing-specific-package-versions-with-pip
Pourquoi le wildcard du coup ?

**Comment by f-l-s** [comment]
> On va modifier le plugin pour palier au problème.
> 
> Pour le développeur grincheux, c'est une private joke, on a eu un petit conflit avec Lunarok pour ne pas le citer

OK. Génial. Merci ! :)

**Comment by llaumgui** [comment]
Moyen de tester cette commande: `python3 -m pip install zigate==$zigate_version.* --upgrade` (dsl pas de Jessie sous la main).
Et de me donner ta version de pip ?

**Comment by doudz** [comment]
> Moyen de tester cette commande: `python3 -m pip install zigate==$zigate_version.* --upgrade` (dsl pas de Jessie sous la main).
> Et de me donner ta version de pip ?

ça donnera rien, $zigate_version n'est défini que dans le script d'installation.
Je pense que la version est 1.5.6

Ce qui plante c'est 
`python3 -m pip install  zigate==0.22.0.*`
Il faudrait remplacer par : `python3 -m pip install zigate==0.22.0`

**Comment by llaumgui** [comment]
Yes, merci de la correction, j'ai tester sur mon jeedom mais j'aibpas mis la bonne commande en copier / coller 😀

**Comment by llaumgui** [comment]
C'est même 0.24.2

**Comment by doudz** [comment]
J'ai poussé la modif en beta directement

**Comment by llaumgui** [comment]
J'aurais préféré une validation... Entre le pop de Jessie, le 9 de Stretch et la dernière version qui est la 18...

**Comment by doudz** [comment]
Si tu préfères, retires le commit et passe le en dev.
Mais j'ai pensé qu'il fallait aller vite pour corriger le problème.

**Comment by llaumgui** [comment]
Pas de soucis, j'ai fait un bump de version et je vais le merge dans master...

**Comment by f-l-s** [comment]
Merci beaucoup pour votre correctif. Ca fonctionne bien sur Jeedom Mini après mise à jour.
:)
Beau cadeau de fin d'année. Merci encore !
